<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BibliographieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibliographieV1Repository extends \Doctrine\ORM\EntityRepository {

    public function getBibliographieToConfirm() {
        $q = $this->_em->createQuery("SELECT b FROM AppBundle:BibliographieV1 b WHERE b.confirmed = 0")
            ->setMaxResults(1);

        return $q->getSingleResult();
    }
}
