<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use AppBundle\Entity\Topic;


/**
 * BibliographieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibliographieRepository extends \Doctrine\ORM\EntityRepository {
}
