<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BibliographieV1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibliographieV1Repository extends \Doctrine\ORM\EntityRepository {

    public function getBibliographieToConfirm() {
        $q = $this->_em->createQuery("SELECT b FROM AppBundle:BibliographieV1 b WHERE b.confirmed = 0")
            ->setMaxResults(1);

        return $q->getSingleResult();
    }

    public function setConfirmed($id){
        $qb = $this->_em->createQueryBuilder();
        $q = $qb->update('AppBundle:BibliographieV1', 'b')
            ->set("b.confirmed", "1")
            ->where("b.id = :id")
            ->setParameter("id", $id)
            ->getQuery();

        return $q->execute();
    }
}
